// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctuvwdsoamgrfcnoelkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0dXZ3ZHNvYW1ncmZjbm9lbGtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDQyNjUsImV4cCI6MjA1OTMyMDI2NX0.HpL3pVV4RooAaTph6lN_dhNO6mrbCGfmYz_52g6NaIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);